name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Passo para garantir que o repositório seja clonado

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven' # <-- AQUI VOCÊ ESPECIFICA O CACHE DO MAVEN

    - name: Build with Maven
      run: mvn -B package
